                </div> <!-- Right DIV -->
        </div> <!-- Content DIV -->
        <div id="footer">
			<a target="_blank" href="http://www.nevadaport.com" color="black" >   
			www.nevadaport.com 2010 Her Hakkı Saklıdır 
			</a>
			
			<a target="_blank" href="http://www.linuxprogramlama.com" color="black" >   
			Destek ve Forum adresi  www.linuxprogramlama.com 
			<br/>			
		</div> <!-- Footer DIV -->
</div> <!-- Wrapper Div -->
<script type="text/javascript" src="/themes/<?php echo $g['theme']; ?>/bottom-loader.js"></script>

